title: Kassimou Abdoul Haki Maoude
email: abdoulhaki.maoude@aiesec.net
description: Postdoctoral researcher in Statistics and Machine Learning
url: "https://abdoulmaoude.github.io/"  # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: abdoulmaoude
github_username:  abdoulmaoude
theme: jekyll-theme-minimal
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-feed
